In [1]:
import re
import pandas as pd

In [2]:
with open('LOG3.TXT','r') as f:
    dat = f.readlines()
    

In [3]:
dat

['28.10.2016\r\n',
 '10:23:01\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:23:17\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:23:33\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:23:49\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:24:05\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:24:21\r\n',
 'a/g:\t0\t0\t0\r\n',
 '\tReinitializing\r\n',
 '28.10.2016\r\n',
 '10:24:38\r\n',
 'a/g:\t0\t0\t0\r\n',
 '\tReinitializing\r\n',
 '28.10.2016\r\n',
 '10:24:54\r\n',
 'a/g:\t0\t0\t0\r\n',
 '\tReinitializing\r\n',
 '28.10.2016\r\n',
 '10:25:10\r\n',
 'a/g:\t0\t0\t0\r\n',
 '\tReinitializing\r\n',
 '\tReinitializing\r\n',
 '28.10.2016\r\n',
 '10:25:42\r\n',
 'a/g:\t0\t0\t0\r\n',
 '\tReinitializing\r\n',
 '28.10.2016\r\n',
 '10:25:58\r\n',
 'a/g:\t-7976\t13620\t2652\r\n',
 '\t28.10.2016\r\n',
 '10:26:15\r\n',
 'a/g:\t12984\t1484\t1652\r\n',
 '\t28.10.2016\r\n',
 '10:26:31\r\n',
 'a/g:\t9028\

In [4]:
len(dat)

4852

In [6]:
#dat[8333]

In [7]:
dat[-2]

'a/g:\t14988\t10048\t-5584\r\n'

In [8]:
corrupt_indices = [jdx for jdx,j in enumerate([re.findall('Rein',i) for i in dat]) if len(j)==1]
dat_cleaned = [i for idx,i in enumerate(dat) if idx not in corrupt_indices]

In [9]:
dat_cleaned

['28.10.2016\r\n',
 '10:23:01\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:23:17\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:23:33\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:23:49\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:24:05\r\n',
 'a/g:\t-10684\t-11756\t-2492\r\n',
 '\t28.10.2016\r\n',
 '10:24:21\r\n',
 'a/g:\t0\t0\t0\r\n',
 '28.10.2016\r\n',
 '10:24:38\r\n',
 'a/g:\t0\t0\t0\r\n',
 '28.10.2016\r\n',
 '10:24:54\r\n',
 'a/g:\t0\t0\t0\r\n',
 '28.10.2016\r\n',
 '10:25:10\r\n',
 'a/g:\t0\t0\t0\r\n',
 '28.10.2016\r\n',
 '10:25:42\r\n',
 'a/g:\t0\t0\t0\r\n',
 '28.10.2016\r\n',
 '10:25:58\r\n',
 'a/g:\t-7976\t13620\t2652\r\n',
 '\t28.10.2016\r\n',
 '10:26:15\r\n',
 'a/g:\t12984\t1484\t1652\r\n',
 '\t28.10.2016\r\n',
 '10:26:31\r\n',
 'a/g:\t9028\t-14212\t-2368\r\n',
 '\t28.10.2016\r\n',
 '10:26:47\r\n',
 'a/g:\t9032\t-14144\t-2464\r\n',
 '\t28.10.2016\r\n',
 '10:27:03\r\n',
 'a/g:\t8992\t-1412

In [10]:
dat = dat_cleaned

In [11]:
date=list()
time=list()
acc=list()

In [12]:
time

[]

In [13]:
len(dat)

4846

In [14]:
dat_trim = dat[0:(len(dat)-len(dat)%3)]

In [15]:
len(dat_trim)

4845

In [16]:
for i in range(0,len(dat_trim),3):
    date =  date+[dat_trim[i]]
    time = time+[dat_trim[i+1]]
    acc = acc+[dat_trim[i+2]]

In [17]:
time_fmt = [i.replace('\r\n','') for i in time]


In [18]:
   time_fmt

['10:23:01',
 '10:23:17',
 '10:23:33',
 '10:23:49',
 '10:24:05',
 '10:24:21',
 '10:24:38',
 '10:24:54',
 '10:25:10',
 '10:25:42',
 '10:25:58',
 '10:26:15',
 '10:26:31',
 '10:26:47',
 '10:27:03',
 '10:27:19',
 '10:27:35',
 '10:27:51',
 '10:28:07',
 '10:28:24',
 '10:28:40',
 '10:28:56',
 '10:29:12',
 '10:29:28',
 '10:29:44',
 '10:30:00',
 '10:30:17',
 '10:30:33',
 '10:30:49',
 '10:31:05',
 '10:31:21',
 '10:31:37',
 '10:31:53',
 '10:32:09',
 '10:32:26',
 '10:32:42',
 '10:32:58',
 '10:33:14',
 '10:33:30',
 '10:33:46',
 '10:34:02',
 '10:34:19',
 '10:34:35',
 '10:34:51',
 '10:35:07',
 '10:35:23',
 '10:35:39',
 '10:35:55',
 '10:36:11',
 '10:36:28',
 '10:36:44',
 '10:37:00',
 '10:37:16',
 '10:37:32',
 '10:37:48',
 '10:38:04',
 '10:38:21',
 '10:38:37',
 '10:38:53',
 '10:39:09',
 '10:39:25',
 '10:39:41',
 '10:39:57',
 '10:40:13',
 '10:40:30',
 '10:40:46',
 '10:41:02',
 '10:41:18',
 '10:41:34',
 '10:41:50',
 '10:42:06',
 '10:42:23',
 '10:42:39',
 '10:42:55',
 '10:43:11',
 '10:43:27',
 '10:43:43',

In [19]:
#time_idx = time_fmt.index()

In [20]:
#face_entry = np.mean(np.array(acc_int[time_idx:time_idx+10]),axis=0)

In [21]:
#np.argmin([np.linalg.norm(face_entry- i )for i in clusters])

In [22]:
#re.findall('\d\\t(.*?)\\r',acc[0])

In [23]:
acc_int = [[int(i.replace('\r\n','')) for i in j.split('\t')[1:4] ] for j in acc]

In [24]:
#acc[0]

In [25]:
acc_int[0:10]

[[-10684, -11756, -2492],
 [-10684, -11756, -2492],
 [-10684, -11756, -2492],
 [-10684, -11756, -2492],
 [-10684, -11756, -2492],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0],
 [0, 0, 0]]

In [26]:
#plotting

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

In [27]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt



fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

x =[i[0] for i in acc_int]
y =[i[1] for i in acc_int]
z =[i[2] for i in acc_int]



ax.scatter(x, y, z, c='r', marker='o')

ax.set_xlabel('X Label')
ax.set_ylabel('Y Label')
ax.set_zlabel('Z Label')

plt.show()

In [28]:
#clustering

from sklearn.cluster import KMeans
import numpy as np

In [29]:
X = np.array(acc_int)

In [30]:
X

array([[-10684, -11756,  -2492],
       [-10684, -11756,  -2492],
       [-10684, -11756,  -2492],
       ..., 
       [  9180, -13932,  -2160],
       [  9152, -14036,  -2108],
       [ 14988,  10048,  -5584]])

In [31]:
kmeans = KMeans(n_clusters=6, random_state=0).fit(X)

In [32]:
kmeans.labels_
#array([0, 0, 0, 1, 1, 1], dtype=int32)

array([4, 4, 4, ..., 1, 1, 3], dtype=int32)

In [33]:
#kmeans.predict([[0, 0], [4, 4]])
#array([0, 1], dtype=int32)

In [34]:
clusters = kmeans.cluster_centers_
#array([[ 1.,  2.],
#       [ 4.,  2.]])

In [35]:
clusters

array([[ -9039.52112676,  12861.56338028,   2011.70422535],
       [  9066.17270195, -14163.00835655,  -2172.98050139],
       [  7868.33121019,   2165.30785563,  14954.28450106],
       [ 12263.54347826,   8263.13043478,  -7714.86956522],
       [ -8850.33333333,  -7541.33333333,   3935.33333333],
       [ -6705.77777778,  -2484.44444444, -14611.55555556]])

In [36]:
#find face for all entries
face_recording = [np.argmin([np.linalg.norm(face_entry- i )for i in clusters]) for face_entry in acc_int]

In [37]:
time_face = zip(time_fmt,face_recording)
with open('time_face2.csv','wb') as thefile:
    for item in time_face:
        thefile.write("{0}\n".format(item))

In [22]:
dat[0:1]

['26.10.2016\r\n']

In [23]:
(len(dat)-len(dat)%3)

8334

In [24]:
len(dat)%3

1